version: '3'

services:
  frontend_thealfastore:
    container_name: frontend
    image: frontend
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      - VITE_API_URL=https://api.alfastoreargentina.com